# Generated by Django 5.2.5 on 2025-08-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_trackedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedlink',
            name='custom_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
