# Generated by Django 5.2.5 on 2025-08-07 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_trackedlink_custom_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.trackedlink')),
            ],
        ),
    ]
